### ISSUE TITLE
Can't publish: (intermediate value)[t] is undefined

### ISSUE THREAD

**Issue by Melkor333** [silverbulletmd/silverbullet-ghost#5]
Hey

I tried to publish a post and a page to a new personal blog (just set up from scratch) and I get the following error:
```javascript
TypeError: (intermediate value)[t] is undefined
    publish https://silver.yosemitesam.ch/_plug/ghost.plug.js:1
```

I tried to create a new post and update the `about` page, both didn't really work :(
Here is the console output when I try to update the page:

![image](https://github.com/silverbulletmd/silverbullet-ghost/assets/6412377/f74ba02a-d2e5-4c5d-96f7-75fb5ffc8445)

I honestly don't really know how to debug this.

I kinda assume it's a problem with my `SECRETS` file, but I'm not sure. The content of it is (obviously without the backslash at the end):
```
My secrets!

```yaml
ghost:
  myblog: 'redacted'
\```
```
I just added the `My secrets!` to see if it changes something - it doesn't

**Comment by zefhemel** [comment]
Yeah it broke for me too. Could you try updating your plugs (`Plugs: Update`) command and see if that fixes it (just pushed a new build)

**Comment by Melkor333** [comment]
Thanks for the quick update!
Sadly it still doesn't work. I tested in Firefox and Chrome.
They both show the same in the Web UI:
```
Unsupported publisher: ghost for URI: ghost:blog:post:nyxt-first-impressions
```
But in the dev tools the erorr differs. Apparently Firefox still gives the "old" error, while chrome gives a different one.
Firefox:
```javascript
An exception was thrown as a result of invoking function publish error: TypeError: (intermediate value)[t] is undefined
    publish https://silver.yosemitesam.ch/_plug/ghost.plug.js:1
[ghost.plug.js:1:994](https://silver.yosemitesam.ch/_plug/ghost.plug.js)
    R https://silver.yosemitesam.ch/_plug/ghost.plug.js:1
Error dispatching event share:ghost to plug ghost: (intermediate value)[t] is undefined [event.ts:69:26](https://silver.yosemitesam.ch/plugos/hooks/event.ts)
    dispatchEvent event.ts:69
```

Chrome:
```javascript
An exception was thrown as a result of invoking function publish error: TypeError: Cannot read properties of undefined (reading '0')
    at b.publish (ghost.plug.js:1:10070)
    at async G (ghost.plug.js:1:10756)
    at async ghost.plug.js:1:903
(anonymous) @ ghost.plug.js:1
await in (anonymous) (async)
(anonymous) @ ghost.plug.js:1
event.ts:69 Error dispatching event share:ghost to plug ghost: Cannot read properties of undefined (reading '0')
```

**Comment by Melkor333** [comment]
Soo I recompiled the `silverbullet-ghost` js file with `--debug` and got a bit of a better error message.
I now get the following request replies for the following URL (I only got 401 errors before, not sure how that got fixed):
```
GET https://silver.yosemitesam.ch/!blog.yosemitesam.ch/ghost/api/v3/admin/posts/slug/nyxt-first-impressions
404
POST https://silver.yosemitesam.ch/!blog.yosemitesam.ch/ghost/api/v3/admin/posts
422
```

Within the HTTP 422 error I get the following response:
```json
{"errors":[{"message":"Validation error, cannot save post.","context":"Validation failed for posts.","type":"ValidationError","details":[{"keyword":"required","dataPath":"","schemaPath":"#/required","params":{"missingProperty":"posts"},"message":"should have required property 'posts'"}],"property":"posts","help":null,"code":null,"id":"6ed18370-6f08-11ee-9d15-8ffa5e3e4598","ghostErrorCode":null}]}
```

And this is the stacktrace
```
Error dispatching event share:ghost to plug ghost: (intermediate value)[what] is undefined [event.ts:69:26](https://silver.yosemitesam.ch/plugos/hooks/event.ts)
    dispatchEvent event.ts:69
    dispatch event.ts:7
    syscallWithContext system.ts:80
    syscall plug.ts:44
    onMessage sandbox.ts:47
    onmessage sandbox.ts:38
```

I'm not sure I'm misinterpreting the Firefox devtools, but it seems to me it's doing a completely empty POST to `https://silver.yosemitesam.ch/!blog.yosemitesam.ch/ghost/api/v3/admin/posts` after it get's a 404 for the `https://silver.yosemitesam.ch/!blog.yosemitesam.ch/ghost/api/v3/admin/posts/slug/nyxt-first-impressions` (which I assume is a check to see if a post already exists) 🤔 

The server seems to proxy it properly, this is all I see in its logs:

```
Requested path to proxy blog.yosemitesam.ch/ghost/api/v3/admin/posts/slug/nyxt-first-impressions GET
Requested path to proxy blog.yosemitesam.ch/ghost/api/v3/admin/posts POST
```


I tried with a page containing pictures and one with really only very basic text - to make sure this doesn't break anything.

**Comment by zefhemel** [comment]
Odd. What do you have in your page's frontmatter? Specifically the `$share` key?

**Comment by Melkor333** [comment]
To make sure I made no mistake I literally copied the suggestions in the [README](https://github.com/silverbulletmd/silverbullet-ghost):
```yaml
---
$share:
- ghost:myblog:post:my-post-slug
---
```
and
```yaml
---
$share:
- ghost:myblog:page:my-page-slug
---
```

Which gave me these errors (on a test page without any images or the like. I wasn't sure if images are supported).

The "original" is this:
```yaml
---
$share:
  ghost:myblog:post:nyxt-first-impressions
---
```

Which gives the exactly same error (even with the missing `-` making it a dict instead of an array I guess)

Edit: There's also another stacktrace in the `plug.js` just before the one I sent before. I somehow missed copying it...

```javascript
TypeError: (intermediate value)[what] is undefined
    publish https://silver.yosemitesam.ch/_plug/ghost.plug.js:746
[ghost.plug.js:110:25](https://silver.yosemitesam.ch/_plug/ghost.plug.js)
    setupMessageListener https://silver.yosemitesam.ch/_plug/ghost.plug.js:110
Error dispatching event share:ghost to plug ghost: (intermediate value)[what] is undefined [event.ts:69:26](https://silver.yosemitesam.ch/plugos/hooks/event.ts)
    dispatchEvent event.ts:69
    dispatch event.ts:7
    syscallWithContext system.ts:80
    syscall plug.ts:44
    onMessage sandbox.ts:47
    onmessage sandbox.ts:38
```

**Comment by AudunVN** [comment]
Spent some time trying to get this plug to work today after running into the same issue. Now have a (seemingly) working fork at [AudunVN/silverbullet-ghost](https://github.com/AudunVN/silverbullet-ghost), will try submit a pull request when I manage to figure out exactly what actually made it work in the end - my latest working commit is [frustratingly close](https://github.com/silverbulletmd/silverbullet-ghost/compare/dcc8432...AudunVN:silverbullet-ghost:8752abb) to https://github.com/silverbulletmd/silverbullet-ghost/commit/dcc84320eb49c70923109c44a3baaeda37633bf4.

My current feeling is that it seems like Ghost may have had some subtle breaking changes related to Lexical and/or their Admin API recently, had difficulties getting even a minimal example based on their [docs](https://ghost.org/docs/admin-api/#creating-a-post) to work including the HTML source approach. Also seen some other unresolved reports of people having seemingly similar issues with the API - such as https://github.com/TryGhost/Ghost/issues/18948#issuecomment-1859196207 - but like I've found while trying to debug this plug it's unfortunately difficult to get feedback or useful errors from Ghost (v5.81). It often seemingly happily accepts POST/PUT requests to `/ghost/api/v3/admin/posts/` and `/ghost/api/v3/admin/pages/`, returns a 200/201 code (and even sometimes updates the page title from `title`), but doesn't seem to do anything with the `lexical` and/or `html` fields in the request. Makes it pretty difficult to be certain where the issue lies.

**Comment by zefhemel** [comment]
I'm using this plug weekly and it all works fine for me. But I'll look at your fork.

**Comment by AudunVN** [comment]
Thanks! I don't think my fork is all that relevant any more, since after further testing today I can no longer reproduce this issue with the current version of the plug (https://github.com/silverbulletmd/silverbullet-ghost/commit/dcc84320eb49c70923109c44a3baaeda37633bf4) and Ghost v5.81.1. Think this issue might be restricted to an older version of Ghost or something else outside the plug itself.

Would have been interesting to know which version of Ghost @Melkor333 was using, but even if the exact cause of the original issue isn't found it's good to know that it doesn't appear to affect the latest versions of Ghost, SilverBullet and silverbullet-ghost.

PS: Thank you very much for your work on all this! I have for a very long time been trying to find a good self-hosted cross-platform method for editing and managing my existing Markdown notes, and also been looking for a quick and low-friction method for eventually getting text from those notes into posts on a new personal website. It was very nice to find that SilverBullet could solve *both* problems (and much more) while also managing to be easy to get started with and extend as needed.

**Comment by Melkor333** [comment]
Heya, just tested again and it works for me now, too. I can't really say what version I used back then but I guess it doesn't really matter :)

From my side also a big fat thanks for keep working on it. It's such a great tool!

**Comment by cterence** [comment]
Sorry for adding to a closed issue, but I had the same underfined error and it turns out that you have to specify another yaml section in the settings for this plugin to work.

In the settings page, you have the space-config block :

```space-config
indexPage: "[[index]]"
libraries:
- import: "[[!silverbullet.md/Library/Core/*]]"
```

You must not add the ghost settings there, you have to add a new yaml block :

```yaml
ghost:
  myblog:
    url: https://your-ghost-blog.ghost.io
```

That's very subtle and breaks in an unexpected way, but now it works for me!

**Comment by zefhemel** [comment]
This is a very different issue, but let me repurpose this.

**Comment by zefhemel** [comment]
If you update the plug, this should no longer be an issue.
